### PR TITLE
Add tests for libyear, using pytest-vcr for reproducable output

### PR DESCRIPTION
**Pull request by kbakk**
I've added [pytest-vcr](https://pypi.org/project/pytest-vcr/) / [VCR.py](https://vcrpy.readthedocs.io/en/latest/) to enable a reproducible e2e style test: checking that the output of libyear doesn't change. 

The test may require some maintenance - e.g. if a change in how requests against PyPI are done, the cassette will have to be updated. Same goes if output format is changed.

### CODE REVIEW

**Comment by kbakk** [comment]
I notice that the GitHub action isn't running, it seems like "Run workflows from fork pull requests" needs to be enabled.

https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#enabling-workflows-for-private-repository-forks"

**Review by nasirhjafri — COMMENTED** [review]
Thanks @kbakk for the testcases. Do we need this file?
`tests/cassettes/tests.test_libyear/test_libyear_main_output.yaml`

**Comment by kbakk** [comment]
Yes, it contains the PyPI responses that VCR.py is mocking.

If the file is removed, the test will use the real PyPI and the YAML will be recreated.

The idea is to ensure that the output doesn't change.

**Comment by fbernhart** [comment]
> I notice that the GitHub action isn't running, it seems like "Run workflows from fork pull requests" needs to be enabled.
> 
> https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#enabling-workflows-for-private-repository-forks"

@kbakk It should run once #26 is merged. Seems like your link doesn't apply, as it's not a private repository. All that was necessary was to add `on: [pull_request, push]` to the GitHub action workflow. 😊

**Review by nasirhjafri — APPROVED** [review]

**Comment by nasirhjafri** [comment]
Thanks @kbakk

**Pull request merged**
